#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
INDEX = ROOT / "index.html"

ROWS = {
    "Indiana — Allen County 2026": r'''{state:'Indiana — Allen County 2026',product:'Tax sale certificate / property-tax lien',schedule:'Allen County\'s official 2026 tax sale is <span class="schedule-date">September 16, 2026</span>. The county currently labels its 2026 Tax Sale List as updated August 20, 2026; eligibility remains dynamic as owners redeem/pay before sale.',availability:'Upcoming — official 2026 list published',interest:'Redemption payments and purchaser return are governed by Indiana Code 6-1.1-24 and 6-1.1-25. Indiana State Board of Accounts guidance describes 110% of the minimum bid for redemption within six months and 115% after six months but before one year, plus 10% annual interest on qualifying amounts above the minimum bid and certain later taxes/assessments. Verify the current county handout for the specific sale.',bid:'https://www.allencounty.in.gov/270/Tax-Sale',canadian:'Not confirmed — verify current Allen County/GovEase bidder-registration and U.S. taxpayer-form requirements before participating',itin:'Do not assume an ITIN alone is sufficient; verify the sale vendor\'s current registration requirements',online:'Allen County publishes current 2026 sale instructions on its official Tax Sale page; verify the linked current-year handout before registering',otc:'NO for the annual tax sale; Allen County notes that certain unsold parcels may later be handled through the county/ACCDC process, which is a different disposition path',deed:'Purchaser receives a tax-sale certificate/lien first. A tax deed is not immediate; statutory redemption and notice procedures apply.',special:'MARKET-LEVEL SUMMARY ONLY. Allen County warns that federal tax liens may survive unless the purchaser separately obtains a federal Certificate of Discharge. Treat the county\'s current list as dynamic because parcels can be removed before sale. Do not bulk republish owner names or treat a prior snapshot as guaranteed current inventory.',source:'https://www.allencounty.in.gov/270/Tax-Sale'}''',
    "Indiana — Lake County 2026": r'''{state:'Indiana — Lake County 2026',product:'Tax sale certificate / property-tax lien',schedule:'Lake County\'s official 2026 electronic tax sale begins <span class="schedule-date">September 4, 2026</span> at 5:30 PM local time, with properties closing in batches beginning September 7, 2026. Registration for this annual sale closed August 14, 2026.',availability:'Upcoming — official 2026 tax-sale notice and public property-list link published',interest:'Indiana redemption mechanics are not a simple APR. Lake County states redemption is 110% of the minimum bid if redeemed within six months or 115% after six months but before one year, plus the purchase-price excess over the minimum bid and 5% annual interest on that excess; qualifying later taxes/assessments paid by the purchaser also earn 5% annual interest. Verify the current county notice and Indiana Code for the exact parcel.',bid:'https://lakecountyin.gov/departments/treasurer/lake-county-tax-sale-notice-2026',canadian:'Annual-auction registration requires IRS Form W-9 and county/vendor approval. A non-U.S. person should not assume W-8 or an ITIN is accepted; verify eligibility directly with Lake County before relying on the auction.',itin:'Do not assume an ITIN alone satisfies the annual-auction W-9 requirement. Business entities must also meet Lake County\'s stated Indiana certificate-of-existence/foreign-registration requirement.',online:'YES — Lake County states the 2026 tax sale is conducted electronically through ZeusAuction. The county also links a public SRI property list; do not bypass auction registration controls.',otc:'NO for the annual tax sale. County-struck certificates and later certificate-sale/disposition processes are legally distinct and should not be treated as the September annual auction.',deed:'Purchaser receives a tax-sale certificate/lien first. A tax deed is not immediate; Lake County states a redemption period applies and later deed procedures are governed separately by Indiana law.',special:'MARKET-LEVEL SUMMARY ONLY. Lake County publishes a current tax-sale notice and a public SRI property-list link, but the county warns that eligibility and minimum bid amounts can change before auction. The statutory minimum bid is based on delinquent/current taxes, penalties, prescribed costs, and certain prior-sale costs. Do not bulk republish owner names, do not infer a stale parcel list as guaranteed auction inventory, and do not confuse Sheriff/judicial foreclosure sales with this Treasurer tax sale.',source:'https://lakecountyin.gov/departments/treasurer/lake-county-tax-sale-notice-2026'}''',
    "Indiana — Porter County 2026": r'''{state:'Indiana — Porter County 2026',product:'Tax sale certificate / property-tax lien',schedule:'Porter County\'s official 2026 Tax Sale will be held online <span class="schedule-date">October 21–22, 2026</span>. The county says additional 2026 sale information will be posted later.',availability:'Upcoming — official 2026 sale dates published; current 2026 parcel results/list not republished here',interest:'Indiana redemption mechanics are statutory penalties/interest rather than a simple APR. Porter County states the standard redemption period after a tax sale is one year; certificate-sale and certain county-held paths use a 120-day redemption period. Verify the current county/SRI handout and Indiana Code 6-1.1-24 and 6-1.1-25 for the exact parcel and sale path.',bid:'https://portercountyin.gov/1036/Tax-SaleCertificate-Sale',canadian:'Not confirmed — verify current Porter County/SRI bidder registration and U.S. taxpayer-form requirements directly before participating.',itin:'Do not assume an ITIN or W-8 alone is accepted; verify the current SRI/Porter County registration requirements.',online:'YES — Porter County states its 2026 Tax Sale will be held online. Use the county page and its official SRI link for current registration and sale details.',otc:'Not a walk-in annual auction. Porter County states unsold tax-sale properties may later be certified to the Board of Commissioners and offered through a separate Certificate Sale, generally in the following spring.',deed:'Purchaser receives a tax-sale certificate/lien first. Porter County separately describes redemption after the tax sale and certificate sale; a tax deed is not immediate.',special:'MARKET-LEVEL SUMMARY ONLY. Porter County Ordinance No. 00-7 states tax-sale results can only be requested in person at the Auditor\'s office and cannot be distributed electronically. Do not bulk republish sale results, owner names, or prior-year parcel lists. Do not infer current 2026 inventory or opening/minimum bids, and do not confuse Sheriff mortgage-foreclosure sales with the Treasurer/Auditor tax sale.',source:'https://portercountyin.gov/1036/Tax-SaleCertificate-Sale'}''',
    "Indiana — Floyd County 2026": r'''{state:'Indiana — Floyd County 2026',product:'Tax sale certificate / property-tax lien',schedule:'Floyd County\'s official 2026 Tax Sale is <span class="schedule-date">October 15, 2026</span>. The county states the sale will be completely online.',availability:'Upcoming — official 2026 sale date and online format published',interest:'Indiana tax-sale purchaser returns are governed by the statutory redemption framework rather than a simple APR. Verify the current Floyd County/SRI sale packet and Indiana Code 6-1.1-24 and 6-1.1-25 for the exact redemption amount, notice obligations, and parcel-specific sale path.',bid:'https://www.in.gov/counties/floyd/department/treasurer/',canadian:'Not confirmed — verify current Floyd County/SRI bidder-registration and taxpayer-document requirements directly before participating.',itin:'Do not assume an ITIN or W-8 alone is accepted; verify Floyd County/SRI\'s current registration requirements.',online:'YES — Floyd County states the 2026 tax sale will be completely online and directs bidders to SRI for registration and sale information.',otc:'Annual tax sale only in this market summary. Floyd County separately adopted a 2026 Commissioners Tax Certificate Sale resolution; do not treat that separate certificate-sale path as identical to the October annual tax sale.',deed:'Purchaser receives a tax-sale certificate/lien first. A tax deed is not immediate; statutory redemption, notice, and deed procedures apply separately under Indiana law.',special:'MARKET-LEVEL SUMMARY ONLY. The official Treasurer page confirms the 2026 date and online format but does not provide a verified unrestricted machine-readable current parcel inventory here. Do not bulk republish owner names, infer current inventory or opening/minimum bids, bypass SRI registration controls, or confuse Sheriff/judicial foreclosure sales with the Treasurer tax sale.',source:'https://www.in.gov/counties/floyd/department/treasurer/'}''',
    "Indiana — Noble County 2026": r'''{state:'Indiana — Noble County 2026',product:'Tax sale certificate / property-tax lien',schedule:'Noble County\'s official 2026 Tax Sale is <span class="schedule-date">October 5, 2026</span> at 10:00 AM in the Noble County Annex Multipurpose Room, 109 N York St, Albion. The Treasurer says the legal advertisement will be posted in August and directs users to the SRI Tax Sale System for current properties.',availability:'Upcoming — official 2026 sale date published; current property eligibility remains dynamic through the official SRI system',interest:'Indiana tax-sale purchaser returns are governed by the statutory redemption framework rather than a simple APR. Verify Noble County\'s current legal advertisement/SRI sale packet and Indiana Code 6-1.1-24 and 6-1.1-25 for the exact redemption amount, notice obligations, and deadlines.',bid:'https://www.in.gov/counties/noble/offices/treasurer/',canadian:'Not confirmed — verify current Noble County/SRI bidder-registration and U.S. taxpayer-document requirements directly before participating.',itin:'Do not assume an ITIN or W-8 alone is accepted; verify Noble County/SRI\'s current registration requirements.',online:'Not stated on the county Treasurer page. Noble County directs investors to the SRI Tax Sale System for current tax-sale properties and additional sale information; do not assume the auction format beyond what the county publishes.',otc:'Not confirmed for this annual sale. Do not treat later county certificate/deed disposition paths as identical to the October tax-sale certificate auction.',deed:'Successful bidder purchases a tax-sale certificate/lien first; a tax deed is not immediate. Statutory redemption, notice, and later deed procedures apply separately under Indiana law.',special:'MARKET-LEVEL SUMMARY ONLY. Noble County publishes the 2026 sale date and directs users to SRI for current properties, but the guide does not bulk republish owner/taxpayer names, freeze a changing list as guaranteed inventory, or infer opening/minimum bids that have not been officially published for a specific parcel. Do not bypass SRI registration controls or substitute Sheriff/judicial foreclosure sales.',source:'https://www.in.gov/counties/noble/offices/treasurer/'}''',
    "Indiana — Scott County 2026": r'''{state:'Indiana — Scott County 2026',product:'Tax sale certificate / property-tax lien',schedule:'Scott County\'s official 2026 tax sale is <span class="schedule-date">September 9, 2026</span>. The county states that real-property parcels with delinquent taxes are offered for a tax certificate sale by the County Treasurer.',availability:'Upcoming — official 2026 sale date and tax-certificate process published; current available-property details are maintained through the county/SRI sale system',interest:'Indiana tax-sale purchaser returns are governed by statutory redemption rather than a simple APR. Scott County states the owner generally has one year after the auction to redeem by paying the amounts prescribed by Indiana Code, including interest on amounts paid by the successful bidder. Verify the current county/SRI sale materials and Indiana Code 6-1.1-24 and 6-1.1-25 for parcel-specific amounts and deadlines.',bid:'https://scottcounty.in.gov/291/Tax-Sales',canadian:'Not confirmed — verify current Scott County/SRI bidder-registration and U.S. taxpayer-document requirements directly before participating.',itin:'Do not assume an ITIN or W-8 alone is accepted; verify Scott County/SRI\'s current registration requirements.',online:'The county directs prospective bidders to SRI for specific auction/property information. Do not assume online format or bypass any vendor registration controls unless confirmed in the current sale materials.',otc:'Not confirmed for the September annual tax sale. Do not treat any later county-held certificate or deed disposition as identical to the annual Treasurer tax-certificate sale.',deed:'Successful bidders obtain a lien through a Tax Sale Certificate issued by the County Auditor. Scott County states that only after the one-year redemption period, and only by following Indiana statutory procedure, may an unredeemed certificate holder seek a tax deed.',special:'MARKET-LEVEL SUMMARY ONLY. Scott County explicitly distinguishes the Treasurer tax-certificate sale from the later tax-deed process. Specific property information is maintained through the official county/SRI path; do not bulk republish owner/taxpayer names, freeze a changing list as guaranteed inventory, infer parcel-level opening/minimum bids, bypass registration controls, or substitute Sheriff/judicial foreclosure sales.',source:'https://scottcounty.in.gov/291/Tax-Sales'}''',
}


def ensure_row(text: str, marker: str, row: str) -> tuple[str, str]:
    if marker in text:
        row_re = re.compile(
            rf"\{{state:'{re.escape(marker)}'.*?\}}(?=\s*,|\s*\n\];)",
            re.S,
        )
        updated, count = row_re.subn(row, text, count=1)
        if count != 1:
            raise SystemExit(f"Could not uniquely refresh {marker}")
        return updated, "Refreshed"

    start = text.find("const rows=[")
    if start < 0:
        raise SystemExit("Could not find rows array")
    end = text.find("\n];", start)
    if end < 0:
        raise SystemExit("Could not find end of rows array")

    before = text[:end]
    after = text[end:]
    insertion = "\n" + row if before.rstrip().endswith(',') else ",\n" + row
    return before + insertion + after, "Added"


def main():
    text = INDEX.read_text(encoding="utf-8")
    actions = []
    for marker, row in ROWS.items():
        text, action = ensure_row(text, marker, row)
        actions.append(f"{action} {marker} tax-lien market")

    INDEX.write_text(text, encoding="utf-8")
    for action in actions:
        print(action)


if __name__ == "__main__":
    main()
